# Generated by Django 4.2.21 on 2025-05-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaignsendlog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['email', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='contact_list',
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_lists',
            field=models.ManyToManyField(blank=True, help_text='Select one or more contact lists for this campaign.', related_name='campaigns', to='mailer_app.contactlist'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, campaign will attempt to send at this time.', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique token for one-click unsubscribe.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='failed_to_send',
            field=models.PositiveIntegerField(default=0, help_text='Number of emails that failed to send for this campaign run.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the campaign sending was completed or last attempted.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='successfully_sent',
            field=models.PositiveIntegerField(default=0, help_text='Number of emails successfully accepted by SES for this campaign run.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0, help_text='Estimated or actual number of recipients targeted by this campaign run.'),
        ),
        migrations.AlterField(
            model_name='campaignsendlog',
            name='email_address',
            field=models.EmailField(help_text='The email address the message was sent to.', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaignsendlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details, if sending failed.', null=True),
        ),
        migrations.AlterField(
            model_name='campaignsendlog',
            name='message_id',
            field=models.CharField(blank=True, help_text='AWS SES Message ID, if successful.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_list',
            field=models.ForeignKey(blank=True, help_text='The list this contact was originally imported into, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mailer_app.contactlist'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Indicates if the contact is currently subscribed to receive emails.'),
        ),
    ]
