# Generated by Django 4.2.21 on 2025-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0002_alter_campaign_options_alter_campaignsendlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='Email address for sending emails', max_length=254, unique=True)),
                ('company_name', models.CharField(help_text='Company name for email signatures', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaignsendlog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignsendlog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='footer_html',
            field=models.TextField(default='<p>---<br>{{your_company_name}}<br><a href="{{unsubscribe_url}}">Unsubscribe</a></p>', help_text='Footer HTML with merge tags like {{unsubscribe_url}}, {{your_company_name}}.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='contact_lists',
            field=models.ManyToManyField(blank=True, help_text='Select one or more contact lists.', related_name='campaigns', to='mailer_app.contactlist'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='failed_to_send',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Send time, if scheduled.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='successfully_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignsendlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsendlog',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Indicates if the contact is currently subscribed.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(help_text='HTML content with merge tags like {{first_name}}.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='Can include merge tags like {{first_name}}.', max_length=255),
        ),
    ]
