# Generated by Django 4.2.21 on 2025-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0003_settings_campaignsendlog_clicked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if the contact is currently subscribed.'),
        ),
    ]
