# Generated by Django 4.2.21 on 2025-05-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0004_alter_contact_email_alter_contact_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='campaignsendlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Campaign Send Log', 'verbose_name_plural': 'Campaign Send Logs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['email', 'created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact List', 'verbose_name_plural': 'Contact Lists'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Application Settings', 'verbose_name_plural': 'Application Settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='company_address',
            field=models.TextField(blank=True, help_text='Physical company address (for CAN-SPAM compliance)', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_url',
            field=models.URLField(blank=True, help_text='Main website URL, e.g., https://www.example.com', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignsendlog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer_app.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='footer_html',
            field=models.TextField(default='<p style="text-align:center; font-size:12px; color:#777;">{{your_company_name}}<br><a href="{{unsubscribe_url}}" style="color:#777; text-decoration:underline;">Unsubscribe</a></p>', help_text='Footer HTML with merge tags like {{unsubscribe_url}}, {{your_company_name}}.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_name',
            field=models.CharField(help_text='Company name for email signatures and footers', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sender_email',
            field=models.EmailField(help_text='Default email address for sending campaigns', max_length=254),
        ),
    ]
