# Generated by Django 4.2.21 on 2025-05-25 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0006_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Active Subscribers'", max_length=255, unique=True)),
                ('filters', models.JSONField(default=dict, help_text="Filter criteria, e.g., {'subscribed': true, 'company': 'Example Inc.', 'custom_fields': {'department': 'Sales'}}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'ordering': ['-created_at'],
            },
        ),
    ]
