# Generated by Django 4.2.21 on 2025-05-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0007_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='segments',
            field=models.ManyToManyField(blank=True, help_text='Select one or more segments.', related_name='campaigns', to='mailer_app.segment'),
        ),
    ]
