# Generated by Django 4.2.21 on 2025-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_app', '0008_campaign_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='filters',
            field=models.JSONField(default=dict, help_text="Filter criteria, e.g., {'subscribed': true, 'company': 'Example Inc.', 'custom_fields': {'department': 'Sales'}, 'contact_lists': ['uuid1', 'uuid2']}"),
        ),
    ]
